#ifndef STRINGS_H
#define STRINGS_H

#ifndef APP_BAES

#define STRINGS_TOTAL_LANGUAGES         5       // 2.4.0, was 4

#define STRINGS_INDEX_PARAMETERS        0
#define STRINGS_INDEX_BASICPARAMETERS   (STRINGS_INDEX_PARAMETERS+STRINGS_TOTAL_LANGUAGES)      // 2.4.0
#define STRINGS_INDEX_ADVANCEDMODE      (STRINGS_INDEX_BASICPARAMETERS+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_FILES             (STRINGS_INDEX_ADVANCEDMODE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_PNL               (STRINGS_INDEX_FILES+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_TEST              (STRINGS_INDEX_PNL+STRINGS_TOTAL_LANGUAGES)             // 2.4.0
#define STRINGS_INDEX_SETTINGS          (STRINGS_INDEX_TEST+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_DATE              (STRINGS_INDEX_SETTINGS+STRINGS_TOTAL_LANGUAGES)        // 2.4.0
#define STRINGS_INDEX_TIMEDELAY         (STRINGS_INDEX_DATE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_HOUR              (STRINGS_INDEX_TIMEDELAY+STRINGS_TOTAL_LANGUAGES)       // 2.4.0

#define STRINGS_INDEX_SENSITIVITY       (STRINGS_INDEX_HOUR+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LOW               (STRINGS_INDEX_SENSITIVITY+STRINGS_TOTAL_LANGUAGES)      //the following 4 items must have fixed sequence and must be treated as one item in placement
#define STRINGS_INDEX_MEDIUM            (STRINGS_INDEX_LOW+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_HIGH              (STRINGS_INDEX_MEDIUM+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_VERYHIGH          (STRINGS_INDEX_HIGH+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_CALIBRATION       (STRINGS_INDEX_VERYHIGH+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_CALIBRATIONPROMPT (STRINGS_INDEX_CALIBRATION+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_DAYLIGHTFACTOR    (STRINGS_INDEX_CALIBRATIONPROMPT+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DAYLIGHTFACTORCEN (STRINGS_INDEX_DAYLIGHTFACTOR+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_NATURALLIGHTFACTOR (STRINGS_INDEX_DAYLIGHTFACTORCEN+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DAYLIGHTLEVEL     (STRINGS_INDEX_NATURALLIGHTFACTOR+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_DAYLIGHTSETPOINT  (STRINGS_INDEX_DAYLIGHTLEVEL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_SETPOINT          (STRINGS_INDEX_DAYLIGHTSETPOINT+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_DETECTIONSCHEME   (STRINGS_INDEX_SETPOINT+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_INITIAL           (STRINGS_INDEX_DETECTIONSCHEME+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_MAINTAIN          (STRINGS_INDEX_INITIAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_RETRIGGER         (STRINGS_INDEX_MAINTAIN+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DISABLED          (STRINGS_INDEX_RETRIGGER+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_PIRONLY           (STRINGS_INDEX_DISABLED+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_USONLY            (STRINGS_INDEX_PIRONLY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_PIRANDUS          (STRINGS_INDEX_USONLY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_PIRORUS           (STRINGS_INDEX_PIRANDUS+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_HFONLY            (STRINGS_INDEX_PIRORUS+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_PIRANDHF          (STRINGS_INDEX_HFONLY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_PIRORHF           (STRINGS_INDEX_PIRANDHF+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_ENABLED           (STRINGS_INDEX_PIRORHF+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_MODE              (STRINGS_INDEX_ENABLED+STRINGS_TOTAL_LANGUAGES)         //the following 7 items must have fixed sequence and must be treated as one item in placement
#define STRINGS_INDEX_AUTOONOFF         (STRINGS_INDEX_MODE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_AUTOWALKTHRU      (STRINGS_INDEX_AUTOONOFF+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_MANUALONAUTOOFF   (STRINGS_INDEX_AUTOWALKTHRU+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_MANUALONOFF       (STRINGS_INDEX_MANUALONAUTOOFF+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_PARTIALONGROUPOFF (STRINGS_INDEX_MANUALONOFF+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_AUTOANTICIPATION  (STRINGS_INDEX_PARTIALONGROUPOFF+STRINGS_TOTAL_LANGUAGES)   // 2.3.0
//precir
#define STRING_INDEX_TIMERSWITCH       (STRINGS_INDEX_AUTOANTICIPATION+STRINGS_TOTAL_LANGUAGES)
#define STRING_INDEX_BILEVEL            (STRING_INDEX_TIMERSWITCH+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_ALERT             (STRING_INDEX_BILEVEL+STRINGS_TOTAL_LANGUAGES)    // 2.3.0
#define STRINGS_INDEX_AUDIBLE           (STRINGS_INDEX_ALERT+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_LIGHTREGULATION   (STRINGS_INDEX_AUDIBLE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LOOPTYPE          (STRINGS_INDEX_LIGHTREGULATION+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_CLOSELOOP         (STRINGS_INDEX_LOOPTYPE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_OPENLOOP          (STRINGS_INDEX_CLOSELOOP+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_PROVISIONOFLIGHT  (STRINGS_INDEX_OPENLOOP+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_AUTO              (STRINGS_INDEX_PROVISIONOFLIGHT+STRINGS_TOTAL_LANGUAGES)    // 2.4.0

#define STRINGS_INDEX_REFERENT          (STRINGS_INDEX_AUTO+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_GROUP             (STRINGS_INDEX_REFERENT+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_TYPE              (STRINGS_INDEX_GROUP+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_SENSORSTATUS      (STRINGS_INDEX_TYPE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LOAD              (STRINGS_INDEX_SENSORSTATUS+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_ON                (STRINGS_INDEX_LOAD+STRINGS_TOTAL_LANGUAGES)                // 2.4.0
#define STRINGS_INDEX_OFF               (STRINGS_INDEX_ON+STRINGS_TOTAL_LANGUAGES)                  // 2.4.0
#define STRINGS_INDEX_ACTIVE            (STRINGS_INDEX_OFF+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_INACTIVE          (STRINGS_INDEX_ACTIVE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_YES               (STRINGS_INDEX_INACTIVE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_NO_1              (STRINGS_INDEX_YES+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_NO_2              (STRINGS_INDEX_NO_1+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_REGULATION_L      (STRINGS_INDEX_NO_2+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_REGULATION_U      (STRINGS_INDEX_REGULATION_L+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DEROGATION_L      (STRINGS_INDEX_REGULATION_U+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DEROGATION_U      (STRINGS_INDEX_DEROGATION_L+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DETECTION_L       (STRINGS_INDEX_DEROGATION_U+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DETECTION_U       (STRINGS_INDEX_DETECTION_L+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_WALKTHROUGH       (STRINGS_INDEX_DETECTION_U+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_SUNDETECTION      (STRINGS_INDEX_WALKTHROUGH+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_STANDBYLEVEL      (STRINGS_INDEX_SUNDETECTION+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_STANDBYDELAY      (STRINGS_INDEX_STANDBYLEVEL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_NOSTANDBY         (STRINGS_INDEX_STANDBYDELAY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_UNLIMITED         (STRINGS_INDEX_NOSTANDBY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_STANDBYMODE       (STRINGS_INDEX_UNLIMITED+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_SENDCONDITION     (STRINGS_INDEX_STANDBYMODE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_CYCLICAL          (STRINGS_INDEX_SENDCONDITION+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_ONCHANGE          (STRINGS_INDEX_CYCLICAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_ONREQUEST         (STRINGS_INDEX_ONCHANGE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_CHANGEORCYCLICAL  (STRINGS_INDEX_ONREQUEST+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DEADBAND          (STRINGS_INDEX_CHANGEORCYCLICAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_TIMEBASE          (STRINGS_INDEX_DEADBAND+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_BANDWIDTH         (STRINGS_INDEX_TIMEBASE+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_SUMMERHOUR        (STRINGS_INDEX_BANDWIDTH+STRINGS_TOTAL_LANGUAGES)           // 2.4.0
#define STRINGS_INDEX_NOCHOICE          (STRINGS_INDEX_SUMMERHOUR+STRINGS_TOTAL_LANGUAGES)          // 2.4.0    //the following 4 items must have fixed sequence and must be treated as one item in placement
#define STRINGS_INDEX_EUROPE            (STRINGS_INDEX_NOCHOICE+STRINGS_TOTAL_LANGUAGES)            // 2.4.0
#define STRINGS_INDEX_USA               (STRINGS_INDEX_EUROPE+STRINGS_TOTAL_LANGUAGES)              // 2.4.0
#define STRINGS_INDEX_NONE              (STRINGS_INDEX_USA+STRINGS_TOTAL_LANGUAGES)                 // 2.4.0
#define STRINGS_INDEX_STARTDAY          (STRINGS_INDEX_NONE+STRINGS_TOTAL_LANGUAGES)                // 2.4.0
#define STRINGS_INDEX_ENDDAY            (STRINGS_INDEX_STARTDAY+STRINGS_TOTAL_LANGUAGES)            // 2.4.0

#define STRINGS_INDEX_COUNTRY           (STRINGS_INDEX_ENDDAY+STRINGS_TOTAL_LANGUAGES)              // 2.4.0

#define STRINGS_INDEX_CURRENTPOL        (STRINGS_INDEX_COUNTRY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_GMT               (STRINGS_INDEX_CURRENTPOL+STRINGS_TOTAL_LANGUAGES)

// 2.2.0
#define STRINGS_INDEX_ROOMCONTROL       (STRINGS_INDEX_GMT+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_REINITIALIZEROOM  (STRINGS_INDEX_ROOMCONTROL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_RETURNTOFACTORY   (STRINGS_INDEX_REINITIALIZEROOM+STRINGS_TOTAL_LANGUAGES)

// 2.2.0
#define STRINGS_INDEX_OTHERPARAMETERS   (STRINGS_INDEX_RETURNTOFACTORY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_BUZZERFEEDBACK    (STRINGS_INDEX_OTHERPARAMETERS+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_POWERLINEFILTER   (STRINGS_INDEX_BUZZERFEEDBACK+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LOADTYPE          (STRINGS_INDEX_POWERLINEFILTER+STRINGS_TOTAL_LANGUAGES)      //the following 8 items must have fixed sequence and must be treated as one item in placement
#define STRINGS_INDEX_FORCEDCAPACITIVE  (STRINGS_INDEX_LOADTYPE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_FORCEDINDUCTIVE   (STRINGS_INDEX_FORCEDCAPACITIVE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_AUTOCAPACITIVE    (STRINGS_INDEX_FORCEDINDUCTIVE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_AUTOINDUCTIVE     (STRINGS_INDEX_AUTOCAPACITIVE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DALI              (STRINGS_INDEX_AUTOINDUCTIVE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DSI               (STRINGS_INDEX_DALI+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LED               (STRINGS_INDEX_DSI+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_SAVEFILE          (STRINGS_INDEX_LED+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_NEWFILE           (STRINGS_INDEX_SAVEFILE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_REPLACEFILE       (STRINGS_INDEX_NEWFILE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_FILESAVED         (STRINGS_INDEX_REPLACEFILE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DEFAULTFILES      (STRINGS_INDEX_FILESAVED+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DEFAULTFILESNA    (STRINGS_INDEX_DEFAULTFILES+STRINGS_TOTAL_LANGUAGES)

// 2.2.0
#define STRINGS_INDEX_CORRIDORHALLAUTO  (STRINGS_INDEX_DEFAULTFILESNA+STRINGS_TOTAL_LANGUAGES)      //the following 12 items must have fixed sequence and must be treated as one item in placement
#define STRINGS_INDEX_CORRIDORHALLMANUAL    (STRINGS_INDEX_CORRIDORHALLAUTO+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_SMALLOFFICEAUTO   (STRINGS_INDEX_CORRIDORHALLMANUAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_SMALLOFFICEMANUAL (STRINGS_INDEX_SMALLOFFICEAUTO+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_MEETINGROOMAUTO   (STRINGS_INDEX_SMALLOFFICEMANUAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_MEETINGROOMMANUAL (STRINGS_INDEX_MEETINGROOMAUTO+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_CLASSROOMAUTO     (STRINGS_INDEX_MEETINGROOMMANUAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_CLASSROOMMANUAL   (STRINGS_INDEX_CLASSROOMAUTO+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_OPENSPACEAUTO     (STRINGS_INDEX_CLASSROOMMANUAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_OPENSPACEMANUAL   (STRINGS_INDEX_OPENSPACEAUTO+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_TOILETAUTO        (STRINGS_INDEX_OPENSPACEMANUAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_TOILETMANUAL      (STRINGS_INDEX_TOILETAUTO+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_WAITSENDING       (STRINGS_INDEX_TOILETMANUAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DELETEFILE        (STRINGS_INDEX_WAITSENDING+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_PNLGROUP          (STRINGS_INDEX_DELETEFILE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_ADDPERIPHERAL     (STRINGS_INDEX_PNLGROUP+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LEARN             (STRINGS_INDEX_ADDPERIPHERAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_END               (STRINGS_INDEX_LEARN+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_ERASE             (STRINGS_INDEX_END+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DELETEGROUP       (STRINGS_INDEX_ERASE+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_LANGUAGES         (STRINGS_INDEX_DELETEGROUP+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_VERSION           (STRINGS_INDEX_LANGUAGES+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_BATTERY           (STRINGS_INDEX_VERSION+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_BATTERYLEVEL      (STRINGS_INDEX_BATTERY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LOWBATTERY        (STRINGS_INDEX_BATTERYLEVEL+STRINGS_TOTAL_LANGUAGES)

#ifndef NO_APPSWITCH
#define STRINGS_INDEX_APPSWITCH         (STRINGS_INDEX_LOWBATTERY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_APPSWITCHPROMPT   (STRINGS_INDEX_APPSWITCH+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_NOAPPFOUND        (STRINGS_INDEX_APPSWITCHPROMPT+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_RESTART           (STRINGS_INDEX_NOAPPFOUND+STRINGS_TOTAL_LANGUAGES)
#endif  // #ifndef NO_APPSWITCH

#ifndef NO_APPSWITCH
#define STRINGS_INDEX_WALKTEST          (STRINGS_INDEX_RESTART+STRINGS_TOTAL_LANGUAGES)
#else
#define STRINGS_INDEX_WALKTEST          (STRINGS_INDEX_LOWBATTERY+STRINGS_TOTAL_LANGUAGES)
#endif  // #ifndef NO_APPSWITCH
#define STRINGS_INDEX_ENDTIMEDELAY      (STRINGS_INDEX_WALKTEST+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_INITIALSTATE      (STRINGS_INDEX_ENDTIMEDELAY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_CONTROL           (STRINGS_INDEX_INITIALSTATE+STRINGS_TOTAL_LANGUAGES)    // 2.3.0
#define STRINGS_INDEX_LIGHTS            (STRINGS_INDEX_CONTROL+STRINGS_TOTAL_LANGUAGES)         // 2.3.0
#define STRINGS_INDEX_AUXILIARIES       (STRINGS_INDEX_LIGHTS+STRINGS_TOTAL_LANGUAGES)          // 2.3.0

#define STRINGS_INDEX_WAITREADING       (STRINGS_INDEX_AUXILIARIES+STRINGS_TOTAL_LANGUAGES)     // 2.3.0
#define STRINGS_INDEX_ERRORREADING      (STRINGS_INDEX_WAITREADING+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_UNKNOWNVALUE      (STRINGS_INDEX_ERRORREADING+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_NOTIMPLEMENTED    (STRINGS_INDEX_UNKNOWNVALUE+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_HELP              (STRINGS_INDEX_NOTIMPLEMENTED+STRINGS_TOTAL_LANGUAGES)
//2.4.3
#define STRINGS_INDEX_MESSAGES         (STRINGS_INDEX_HELP+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LONGITUDE          (STRINGS_INDEX_MESSAGES+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LATITUDE          (STRINGS_INDEX_LONGITUDE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_ALGORITHMIC         (STRINGS_INDEX_LATITUDE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DIGITAL          (STRINGS_INDEX_ALGORITHMIC+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_CENTRALIZED          (STRINGS_INDEX_DIGITAL+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DEVICE_ID          (STRINGS_INDEX_CENTRALIZED+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_CONTROLLER_FIM          (STRINGS_INDEX_DEVICE_ID+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_FIRMWARE                  (STRINGS_INDEX_CONTROLLER_FIM+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_DAUGHTER_BOARD                  (STRINGS_INDEX_FIRMWARE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_SUMMERTIME                  (STRINGS_INDEX_DAUGHTER_BOARD+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_START                 (STRINGS_INDEX_SUMMERTIME+STRINGS_TOTAL_LANGUAGES)

#else

#define STRINGS_TOTAL_LANGUAGES         1

#define STRINGS_INDEX_ADRESSER          0
#define STRINGS_INDEX_TESTER            (STRINGS_INDEX_ADRESSER+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_TESTADRESSAGE     (STRINGS_INDEX_TESTER+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_EFFACER_ADRESSE   (STRINGS_INDEX_TESTADRESSAGE+STRINGS_TOTAL_LANGUAGES)

#define STRINGS_INDEX_SETTINGS          (STRINGS_INDEX_EFFACER_ADRESSE+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_VERSION           (STRINGS_INDEX_SETTINGS+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_BATTERY           (STRINGS_INDEX_VERSION+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_BATTERYLEVEL      (STRINGS_INDEX_BATTERY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_LOWBATTERY        (STRINGS_INDEX_BATTERYLEVEL+STRINGS_TOTAL_LANGUAGES)

#ifndef NO_APPSWITCH
#define STRINGS_INDEX_APPSWITCH         (STRINGS_INDEX_LOWBATTERY+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_APPSWITCHPROMPT   (STRINGS_INDEX_APPSWITCH+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_NOAPPFOUND        (STRINGS_INDEX_APPSWITCHPROMPT+STRINGS_TOTAL_LANGUAGES)
#define STRINGS_INDEX_RESTART           (STRINGS_INDEX_NOAPPFOUND+STRINGS_TOTAL_LANGUAGES)
#endif  // #ifndef NO_APPSWITCH

#ifndef NO_APPSWITCH
#define STRINGS_INDEX_YES               (STRINGS_INDEX_RESTART+STRINGS_TOTAL_LANGUAGES)
#else
#define STRINGS_INDEX_YES               (STRINGS_INDEX_LOWBATTERY+STRINGS_TOTAL_LANGUAGES)
#endif  // #ifndef NO_APPSWITCH
#define STRINGS_INDEX_NO_1              (STRINGS_INDEX_YES+STRINGS_TOTAL_LANGUAGES)

#endif  // #ifndef APP_BAES

extern const unsigned char *strings[];
extern const unsigned char *strings_on_level_titile[];
#endif
